default-balance: 25

# You can use %player% to display player name
messages:
  prefix: "&4[ProjectNation]&r"
  join-message: "%prefix% &a%player% &r&6has joined the game !"
  quit-message: "%prefix% &a%player% &r&6has left the game !"